volumes:
  postgres-data:
    name: postgres-data
  mailpit-data:
    name: mailpit-data
  prometheus_data:
    name: prometheus_data
  grafana-storage:
    name: grafana-storage
  loki-data:
    name: loki-data
  promtail-position:
    name: promtail-position

networks:
  ascent:
    name: ascent
    driver: bridge

services:
  postgres-db:
    image: postgres:18-alpine3.23
    container_name: postgres-db
    environment:
      POSTGRES_DB: chinook
      POSTGRES_USER: chinook
      POSTGRES_PASSWORD: password_772
    ports:
      - "32420:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - ascent

  grafana:
    #image: grafana/grafana-oss:latest
    image: systemdevformations/grafana:12.3.2
    container_name: grafana
    ports:
      - "32400:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      #- GF_SECURITY_ADMIN_PASSWORD=p4ssw0rd
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug # Pour débugger si besoin
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=mailpit:1025
      - GF_SMTP_FROM_ADDRESS=alert@grafana.local
      - GF_SMTP_SKIP_VERIFY=true
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - ascent
  renderer:
    #image: grafana/grafana-image-renderer:latest
    image: systemdevformations/grafana-image-renderer:5
    container_name: renderer
    ports:
      - "8081"
    # Configuration pour éviter les problèmes de mémoire sur AlmaLinux
    environment:
      - ENABLE_METRICS=true
      - BROWSER_BIN=/usr/bin/google-chrome
      - IGNORE_HTTPS_ERRORS=true
    restart: unless-stopped
    depends_on:
      - grafana
    networks:
      - ascent

  mailpit:
    #image: axllent/mailpit:latest
    image: systemdevformations/mailpit:1.29.0
    container_name: mailpit
    environment:
      MP_DATABASE: /data/mailpit.db
      # MP_UI_AUTH_FILE: /data/authfile
    ports:
      - "30025:8025" # Interface Web pour voir les mails
      - "31025:1025" # Port SMTP pour Grafana
    volumes:
      - mailpit-data:/data
    restart: unless-stopped
    networks:
      - ascent

  prometheus:
    hostname: prometheus
    container_name: prometheus
    image: prom/prometheus:v3.5.1
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules.yml:/etc/prometheus/alert.rules.yml
      - prometheus_data:/prometheus
    ports:
      - "32430:9090"
    restart: unless-stopped
    networks:
      - ascent

  alertmanager:
    hostname: alertmanager
    container_name: alertmanager
    image: prom/alertmanager:v0.31.1
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "32440:9093"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - ascent

  node-exporter:
    hostname: node-exporter
    container_name: node-exporter
    image: prom/node-exporter:v1.10.2
    ports:
      - "32450:9100"
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - ascent


  postgres-exporter:
    hostname: postgres-exporter
    container_name: postgres-exporter
    image: quay.io/prometheuscommunity/postgres-exporter
    env_file:
      - .env
    command:
      - "--config.file=/etc/postgres_exporter/postgres_exporter.yml"
      - "--extend.query-path=/etc/postgres_exporter/queries.yaml"
    environment:
      #DATA_SOURCE_URI: "34.163.61.189:32420/chinnok?sslmode=disable"
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_EXPORTER_USER}:${POSTGRES_EXPORTER_PASSWORD}@${POSTGRES_EXPORTER_HOST}:${POSTGRES_EXPORTER_PORT}/${POSTGRES_EXPORTER_DB}?sslmode=${POSTGRES_EXPORTER_SSLMODE}"
      DATA_SOURCE_USER: chinook
      DATA_SOURCE_PASS: password_772
    ports:
      - "9187:9187"
    volumes:
      - ./postgres_exporter.yml:/etc/postgres_exporter/postgres_exporter.yml
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - ascent
  loki:
    image: grafana/loki:3.6.6
    container_name: loki
    ports:
      - "32460:3100"
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    networks:
      - ascent

  # 4. Promtail (Agent de collecte des logs)
  promtail:
    image: grafana/promtail:latest
    user: root
    container_name: promtail
    ports:
      - "32470:9080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:Z
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./promtail-config.yml:/etc/promtail/config.yml
      - promtail-position:/tmp
    command: -config.file=/etc/promtail/config.yml
    networks:
      - ascent