volumes:
  postgres-chinook-data:


services:
  #----------------------------------------------------------------------------
  # PostgreSQL Container
  # https://hub.docker.com/_/postgres
  # Commands:
  #   psql -d chinook -U chinook -W
  #----------------------------------------------------------------------------

  postgres-18:
    image: postgres:18.3-alpine3.23
    container_name: postgres-18
    shm_size: "2gb"
    environment:
      POSTGRES_USER: chinook
      POSTGRES_PASSWORD: password_772
      POSTGRES_DB: chinook
    ports:
      - "32200:5432"
    volumes:
      - postgres-chinook-data:/var/lib/postgresql/data
    restart: unless-stopped