volumes:
  postgres-data:



services:
  #----------------------------------------------------------------------------
  # PostgreSQL Container
  # https://hub.docker.com/_/postgres
  # Commands:
  #   psql -U chinook chinook
  #----------------------------------------------------------------------------
  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-chinook
    shm_size: "2gb"
    environment:
      POSTGRES_USER: chinook
      POSTGRES_PASSWORD: password_772
      POSTGRES_DB: chinook
    ports:
      - "32195:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
