# /etc/promtail/config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: postgresql
    static_configs:
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/postgres-db'
        target_label: container
      - replacement: /var/log/postgresql/*.csv
        target_label: __path__

    pipeline_stages:
      - multiline:
           firstline: '^\d{4}-\d{2}-\d{2}'
           max_wait_time: 3s

      - regex:
          expression: >
            ^(?P<log_time>[^,]+),
            (?P<user_name>[^,]*),
            (?P<database_name>[^,]*),
            (?P<process_id>[^,]*),
            (?P<connection_from>[^,]*),
            (?P<session_id>[^,]*),
            (?P<session_line_num>[^,]*),
            (?P<command_tag>[^,]*),
            (?P<session_start_time>[^,]*),
            (?P<virtual_transaction_id>[^,]*),
            (?P<transaction_id>[^,]*),
            (?P<error_severity>[^,]*),
            (?P<sql_state_code>[^,]*),
            "(?P<message>(?:[^"]|"")*)",
            (?P<detail>[^,]*),
            "(?P<hint>(?:[^"]|"")*)"

      - labels:
          database_name:
          user_name:
          error_severity:
          sql_state_code:
          process_id:
          command_tag:


