/*******************************************************************************
   Chinook Database - Massive Data Generation Master Script
   Script: 00_master_massive_data_generation.sql
   Description: Master script to run all massive data generation scripts for Chinook database.
   DB Server: PostgreSQL
   Author: Generated for extending Chinook database with massive dataset
   
   Expected Final Database Size: 10-20 GB
   - Artists: 50,000+
   - Albums: 200,000+
   - Tracks: 2,000,000+
   - Customers: 100,000+
   - Employees: 50+
   - Invoices: 500,000+
   - Invoice Lines: 5,000,000+
   - Playlists: 50,000+
   - Playlist Tracks: 10,000,000+
********************************************************************************/

/*******************************************************************************
   Chinook Database - Version 1.4.5
   Script: Chinook_PostgreSql_AutoIncrementPKs.sql
   Description: Creates and populates the Chinook database.
   DB Server: PostgreSql
   Author: Luis Rocha
   License: https://github.com/lerocha/chinook-database/blob/master/LICENSE.md
********************************************************************************/

/*******************************************************************************
  WARNING: This file was generated by a tool and changes to this file
           will be lost when this file is regenerated.
********************************************************************************/

/*******************************************************************************
   Drop database if it exists
********************************************************************************/
--DROP DATABASE IF EXISTS chinook;


/*******************************************************************************
   Create database
********************************************************************************/
--CREATE DATABASE chinook;


--\c chinook;


/*******************************************************************************
   Create Tables
********************************************************************************/
CREATE TABLE album
(
    album_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    title VARCHAR(160) NOT NULL,
    artist_id INT NOT NULL,
    CONSTRAINT album_pkey PRIMARY KEY  (album_id)
);

CREATE TABLE artist
(
    artist_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(120),
    CONSTRAINT artist_pkey PRIMARY KEY  (artist_id)
);

CREATE TABLE customer
(
    customer_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    first_name VARCHAR(40) NOT NULL,
    last_name VARCHAR(20) NOT NULL,
    company VARCHAR(80),
    address VARCHAR(70),
    city VARCHAR(40),
    state VARCHAR(40),
    country VARCHAR(40),
    postal_code VARCHAR(10),
    phone VARCHAR(24),
    fax VARCHAR(24),
    email VARCHAR(60) NOT NULL,
    support_rep_id INT,
    CONSTRAINT customer_pkey PRIMARY KEY  (customer_id)
);

CREATE TABLE employee
(
    employee_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    last_name VARCHAR(20) NOT NULL,
    first_name VARCHAR(20) NOT NULL,
    title VARCHAR(30),
    reports_to INT,
    birth_date TIMESTAMP,
    hire_date TIMESTAMP,
    address VARCHAR(70),
    city VARCHAR(40),
    state VARCHAR(40),
    country VARCHAR(40),
    postal_code VARCHAR(10),
    phone VARCHAR(24),
    fax VARCHAR(24),
    email VARCHAR(60),
    CONSTRAINT employee_pkey PRIMARY KEY  (employee_id)
);

CREATE TABLE genre
(
    genre_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(120),
    CONSTRAINT genre_pkey PRIMARY KEY  (genre_id)
);

CREATE TABLE invoice
(
    invoice_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    customer_id INT NOT NULL,
    invoice_date TIMESTAMP NOT NULL,
    billing_address VARCHAR(70),
    billing_city VARCHAR(40),
    billing_state VARCHAR(40),
    billing_country VARCHAR(40),
    billing_postal_code VARCHAR(10),
    total NUMERIC(10,2) NOT NULL,
    CONSTRAINT invoice_pkey PRIMARY KEY  (invoice_id)
);

CREATE TABLE invoice_line
(
    invoice_line_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    invoice_id INT NOT NULL,
    track_id INT NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    quantity INT NOT NULL,
    CONSTRAINT invoice_line_pkey PRIMARY KEY  (invoice_line_id)
);

CREATE TABLE media_type
(
    media_type_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(120),
    CONSTRAINT media_type_pkey PRIMARY KEY  (media_type_id)
);

CREATE TABLE playlist
(
    playlist_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(120),
    CONSTRAINT playlist_pkey PRIMARY KEY  (playlist_id)
);

CREATE TABLE playlist_track
(
    playlist_id INT NOT NULL,
    track_id INT NOT NULL,
    CONSTRAINT playlist_track_pkey PRIMARY KEY  (playlist_id, track_id)
);

CREATE TABLE track
(
    track_id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(200) NOT NULL,
    album_id INT,
    media_type_id INT NOT NULL,
    genre_id INT,
    composer VARCHAR(220),
    milliseconds INT NOT NULL,
    bytes INT,
    unit_price NUMERIC(10,2) NOT NULL,
    CONSTRAINT track_pkey PRIMARY KEY  (track_id)
);



/*******************************************************************************
   Create Primary Key Unique Indexes
********************************************************************************/

/*******************************************************************************
   Create Foreign Keys
********************************************************************************/
ALTER TABLE album ADD CONSTRAINT album_artist_id_fkey
    FOREIGN KEY (artist_id) REFERENCES artist (artist_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX album_artist_id_idx ON album (artist_id);

ALTER TABLE customer ADD CONSTRAINT customer_support_rep_id_fkey
    FOREIGN KEY (support_rep_id) REFERENCES employee (employee_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX customer_support_rep_id_idx ON customer (support_rep_id);

ALTER TABLE employee ADD CONSTRAINT employee_reports_to_fkey
 FOREIGN KEY (reports_to) REFERENCES employee (employee_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX employee_reports_to_idx ON employee (reports_to);

ALTER TABLE invoice ADD CONSTRAINT invoice_customer_id_fkey
    FOREIGN KEY (customer_id) REFERENCES customer (customer_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX invoice_customer_id_idx ON invoice (customer_id);

ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_invoice_id_fkey
    FOREIGN KEY (invoice_id) REFERENCES invoice (invoice_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX invoice_line_invoice_id_idx ON invoice_line (invoice_id);

ALTER TABLE invoice_line ADD CONSTRAINT invoice_line_track_id_fkey
    FOREIGN KEY (track_id) REFERENCES track (track_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX invoice_line_track_id_idx ON invoice_line (track_id);

ALTER TABLE playlist_track ADD CONSTRAINT playlist_track_playlist_id_fkey
    FOREIGN KEY (playlist_id) REFERENCES playlist (playlist_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX playlist_track_playlist_id_idx ON playlist_track (playlist_id);

ALTER TABLE playlist_track ADD CONSTRAINT playlist_track_track_id_fkey
    FOREIGN KEY (track_id) REFERENCES track (track_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX playlist_track_track_id_idx ON playlist_track (track_id);

ALTER TABLE track ADD CONSTRAINT track_album_id_fkey
    FOREIGN KEY (album_id) REFERENCES album (album_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX track_album_id_idx ON track (album_id);

ALTER TABLE track ADD CONSTRAINT track_genre_id_fkey
    FOREIGN KEY (genre_id) REFERENCES genre (genre_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX track_genre_id_idx ON track (genre_id);

ALTER TABLE track ADD CONSTRAINT track_media_type_id_fkey
    FOREIGN KEY (media_type_id) REFERENCES media_type (media_type_id) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX track_media_type_id_idx ON track (media_type_id);

-- Add indexes on FK








-- Connect to chinook database
-- \c chinook;

-- Set global performance optimizations for the entire process
SET synchronous_commit = OFF;
--SET wal_level = minimal;
SET maintenance_work_mem = '1GB';
--SET checkpoint_completion_target = 0.9;
SET temp_buffers = '512MB';
SET work_mem = '256MB';
SET effective_cache_size = '4GB';
SET random_page_cost = 1.1;

-- Create a log table to track progress
CREATE TABLE IF NOT EXISTS data_generation_log (
    id SERIAL PRIMARY KEY,
    script_name VARCHAR(100) NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP,
    status VARCHAR(20) NOT NULL,
    records_generated BIGINT,
    table_size TEXT,
    notes TEXT
);

-- Function to log progress
CREATE OR REPLACE FUNCTION log_generation_progress(script_name TEXT, status TEXT, records_generated BIGINT DEFAULT NULL, table_size TEXT DEFAULT NULL, notes TEXT DEFAULT NULL) RETURNS VOID AS $$
BEGIN
    IF status = 'STARTED' THEN
        INSERT INTO data_generation_log (script_name, start_time, end_time, status, records_generated, table_size, notes)
        VALUES (script_name, clock_timestamp(), NULL, status, records_generated, table_size, notes);
    ELSIF status IN ('COMPLETED', 'FAILED') THEN
        UPDATE data_generation_log 
        SET 
            end_time = clock_timestamp(),
            status = status,
            records_generated = records_generated,
            table_size = table_size,
            notes = notes
        WHERE script_name = script_name AND start_time IS NOT NULL AND end_time IS NULL;
    END IF;
END;
$$ LANGUAGE plpgsql;

/*******************************************************************************
   DATA GENERATION EXECUTION PLAN
********************************************************************************/

DO $$
BEGIN
    RAISE NOTICE '========================================';
    RAISE NOTICE 'CHINOOK MASSIVE DATA GENERATION STARTED';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'This process will generate 10-20 GB of data';
    RAISE NOTICE 'Expected completion time: 30-120 minutes';
    RAISE NOTICE '========================================';
END $$;

-- Log the start of the entire process
DO $$
BEGIN
    PERFORM log_generation_progress('MASSIVE_DATA_GENERATION', 'STARTED');
END $$;

/*******************************************************************************
   STEP 0: Setup Base Data
   Expected: Load base genres, media types, and sample data
   Estimated Time: 1-2 minutes
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'STEP 0: Setting up base data...';
END $$;

\i massive_data/00_setup_base_data.sql

/*******************************************************************************
   STEP 1: Generate Artists and Albums
   Expected: ~50,000 artists, ~200,000 albums
   Estimated Time: 5-15 minutes
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'STEP 1: Generating Artists and Albums...';
END $$;
DO $$
BEGIN
    PERFORM log_generation_progress('01_massive_artists_albums', 'STARTED');
END $$;

\i massive_data/01_massive_artists_albums.sql

-- Log completion
DO $$
BEGIN
    PERFORM log_generation_progress(
        '01_massive_artists_albums', 
        'COMPLETED', 
        (SELECT COUNT(*) FROM artist) + (SELECT COUNT(*) FROM album),
        pg_size_pretty(pg_total_relation_size('artist') + pg_total_relation_size('album')),
        'Artists: ' || (SELECT COUNT(*) FROM artist) || ', Albums: ' || (SELECT COUNT(*) FROM album)
    );
END $$;

DO $$
BEGIN
    RAISE NOTICE 'STEP 1 COMPLETED: % artists, % albums', 
        (SELECT COUNT(*) FROM artist), 
        (SELECT COUNT(*) FROM album);
END $$;

/*******************************************************************************
   STEP 2: Generate Tracks
   Expected: ~2,000,000 tracks
   Estimated Time: 15-45 minutes
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'STEP 2: Generating Tracks...';
END $$;
DO $$
BEGIN
    PERFORM log_generation_progress('02_massive_tracks', 'STARTED');
END $$;

\i massive_data/02_massive_tracks.sql

-- Log completion
DO $$
BEGIN
    PERFORM log_generation_progress(
        '02_massive_tracks', 
        'COMPLETED', 
        (SELECT COUNT(*) FROM track),
        pg_size_pretty(pg_total_relation_size('track')),
        'Tracks: ' || (SELECT COUNT(*) FROM track)
    );
END $$;

DO $$
BEGIN
    RAISE NOTICE 'STEP 2 COMPLETED: % tracks', (SELECT COUNT(*) FROM track);
END $$;

/*******************************************************************************
   STEP 3: Generate Customers and Employees
   Expected: ~100,000 customers, ~50 employees
   Estimated Time: 5-10 minutes
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'STEP 3: Generating Customers and Employees...';
END $$;
DO $$
BEGIN
    PERFORM log_generation_progress('03_massive_customers_employees', 'STARTED');
END $$;

\i massive_data/03_massive_customers_employees.sql

-- Log completion
DO $$
BEGIN
    PERFORM log_generation_progress(
        '03_massive_customers_employees', 
        'COMPLETED', 
        (SELECT COUNT(*) FROM customer) + (SELECT COUNT(*) FROM employee),
        pg_size_pretty(pg_total_relation_size('customer') + pg_total_relation_size('employee')),
        'Customers: ' || (SELECT COUNT(*) FROM customer) || ', Employees: ' || (SELECT COUNT(*) FROM employee)
    );
END $$;

DO $$
BEGIN
    RAISE NOTICE 'STEP 3 COMPLETED: % customers, % employees', 
        (SELECT COUNT(*) FROM customer), 
        (SELECT COUNT(*) FROM employee);
END $$;

/*******************************************************************************
   STEP 4: Generate Invoices and Invoice Lines (Optimized)
   Expected: ~500,000 invoices, ~5,000,000 invoice lines
   Estimated Time: 10-30 minutes (optimized totals update)
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'STEP 4: Generating Invoices and Invoice Lines...';
END $$;
DO $$
BEGIN
    PERFORM log_generation_progress('04_massive_invoices', 'STARTED');
END $$;

\i massive_data/04_massive_invoices.sql

-- Log completion
DO $$
BEGIN
    PERFORM log_generation_progress(
        '04_massive_invoices', 
        'COMPLETED', 
        (SELECT COUNT(*) FROM invoice) + (SELECT COUNT(*) FROM invoice_line),
        pg_size_pretty(pg_total_relation_size('invoice') + pg_total_relation_size('invoice_line')),
        'Invoices: ' || (SELECT COUNT(*) FROM invoice) || ', Invoice Lines: ' || (SELECT COUNT(*) FROM invoice_line)
    );
END $$;

DO $$
BEGIN
    RAISE NOTICE 'STEP 4 COMPLETED: % invoices, % invoice lines', 
        (SELECT COUNT(*) FROM invoice), 
        (SELECT COUNT(*) FROM invoice_line);
END $$;

/*******************************************************************************
   STEP 5: Generate Playlists and Playlist Tracks
   Expected: ~50,000 playlists, ~10,000,000 playlist tracks
   Estimated Time: 10-30 minutes
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'STEP 5: Generating Playlists and Playlist Tracks...';
END $$;
DO $$
BEGIN
    PERFORM log_generation_progress('05_massive_playlists', 'STARTED');
END $$;

\i massive_data/05_massive_playlists.sql

-- Log completion
DO $$
BEGIN
    PERFORM log_generation_progress(
        '05_massive_playlists', 
        'COMPLETED', 
        (SELECT COUNT(*) FROM playlist) + (SELECT COUNT(*) FROM playlist_track),
        pg_size_pretty(pg_total_relation_size('playlist') + pg_total_relation_size('playlist_track')),
        'Playlists: ' || (SELECT COUNT(*) FROM playlist) || ', Playlist Tracks: ' || (SELECT COUNT(*) FROM playlist_track)
    );
END $$;

DO $$
BEGIN
    RAISE NOTICE 'STEP 5 COMPLETED: % playlists, % playlist tracks', 
        (SELECT COUNT(*) FROM playlist), 
        (SELECT COUNT(*) FROM playlist_track);
END $$;

/*******************************************************************************
   FINAL OPTIMIZATION AND STATISTICS
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'STEP 6: Final Optimization and Statistics...';
END $$;

-- Update all table statistics
ANALYZE;
ANALYZE artist;
ANALYZE album;
ANALYZE track;
ANALYZE customer;
ANALYZE employee;
ANALYZE invoice;
ANALYZE invoice_line;
ANALYZE playlist;
ANALYZE playlist_track;
ANALYZE genre;
ANALYZE media_type;

-- Rebuild indexes for better performance
REINDEX DATABASE chinook;

-- Vacuum and analyze all tables
VACUUM ANALYZE;

-- Reset performance settings to defaults
SET synchronous_commit = ON;
--SET wal_level = replica;
SET maintenance_work_mem = '64MB';
--SET checkpoint_completion_target = 0.5;
SET temp_buffers = '8MB';
SET work_mem = '4MB';
SET effective_cache_size = '128MB';
SET random_page_cost = 4.0;

/*******************************************************************************
   GENERATION SUMMARY
*******************************************************************************/
DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE '========================================';
    RAISE NOTICE 'CHINOOK MASSIVE DATA GENERATION COMPLETED';
    RAISE NOTICE '========================================';
END $$;

-- Log completion of the entire process
DO $$
BEGIN
    PERFORM log_generation_progress('MASSIVE_DATA_GENERATION', 'COMPLETED');
END $$;

-- Generate final summary report
SELECT 
    'GENERATION SUMMARY' as report_type,
    '' as table_name,
    '' as record_count,
    '' as table_size,
    '' as notes
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Artist' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('artist')) as table_size,
    '' as notes
FROM artist
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Album' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('album')) as table_size,
    '' as notes
FROM album
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Track' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('track')) as table_size,
    '' as notes
FROM track
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Customer' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('customer')) as table_size,
    '' as notes
FROM customer
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Employee' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('employee')) as table_size,
    '' as notes
FROM employee
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Invoice' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('invoice')) as table_size,
    '' as notes
FROM invoice
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Invoice Line' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('invoice_line')) as table_size,
    '' as notes
FROM invoice_line
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Playlist' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('playlist')) as table_size,
    '' as notes
FROM playlist
UNION ALL
SELECT 
    'TABLE STATISTICS' as report_type,
    'Playlist Track' as table_name,
    COUNT(*)::text as record_count,
    pg_size_pretty(pg_total_relation_size('playlist_track')) as table_size,
    '' as notes
FROM playlist_track
UNION ALL
SELECT 
    'DATABASE TOTAL' as report_type,
    'All Tables' as table_name,
    (SELECT SUM(record_count::bigint) FROM (
        SELECT COUNT(*) as record_count FROM artist
        UNION ALL SELECT COUNT(*) FROM album
        UNION ALL SELECT COUNT(*) FROM track
        UNION ALL SELECT COUNT(*) FROM customer
        UNION ALL SELECT COUNT(*) FROM employee
        UNION ALL SELECT COUNT(*) FROM invoice
        UNION ALL SELECT COUNT(*) FROM invoice_line
        UNION ALL SELECT COUNT(*) FROM playlist
        UNION ALL SELECT COUNT(*) FROM playlist_track
    ) as counts)::text as record_count,
    pg_size_pretty(pg_database_size('chinook')) as table_size,
    'Total database size including indexes' as notes;

-- Show generation log
SELECT 
    script_name,
    start_time,
    end_time,
    EXTRACT(EPOCH FROM (end_time - start_time)) as duration_seconds,
    status,
    records_generated,
    table_size,
    notes
FROM data_generation_log
ORDER BY start_time;

-- Clean up
DROP FUNCTION IF EXISTS log_generation_progress(TEXT, TEXT, BIGINT, TEXT, TEXT);

DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE 'Massive data generation completed successfully!';
    RAISE NOTICE 'Check the generation log above for detailed statistics.';
    RAISE NOTICE '========================================';
END $$;
